[package]
name = "grimoire_project"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.98"
reqwest = { version = "0.12.20", features = ["blocking"] }
scraper = "0.23.1"
tracing = "0.1.41"
tracing-subscriber = "0.3.19"
redb = "2.6.0"
