[package]
name = "basic-test-setup"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[dev-dependencies]
assert_cmd = "2.0.4"
cargo-watch = "8.1.1"
color-eyre = "0.6.1"
