[package]
name = "test_directory_runner"
version = "0.1.0"
edition = "2024"

[dependencies]
pretty_assertions = "1.4.1"
macros_for_test_directory_runner = { version = "0.1.0", path = "../macros_for_test_directory_runner" }

[lib]
doctest = false
