[package]
name = "test_runner"
version = "0.1.0"
edition = "2024"

[dependencies]
pretty_assertions = "1.4.1"
test_runner_macros = { version = "0.1.0", path = "../test_runner_macros" }

[lib]
doctest = false
