[package]
name = "logging_with_tracing_subscriber"
version = "0.1.0"
edition = "2024"

[dependencies]
tracing = "0.1.41"
tracing-appender = "0.2.3"
tracing-subscriber = {version= "0.3.19", features = ["fmt", "json", "registry", "std"]}

