[package]
name = "get_list_of_files_recursively"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.98"
itertools = "0.14.0"
walkdir = "2.5.0"

[dev-dependencies] 
pretty_assertions = "1.4.1"

